// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgvvqzlhamcknfpsrcon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndnZxemxoYW1ja25mcHNyY29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzcwMTUsImV4cCI6MjA3MzQxMzAxNX0.xknIBeKUsiUbXA-bf-jy1lTl7VGdAOXFR8Z3V7YjNLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});